import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tools: [{type: 'autogenerated', dirName: 'tools'}],
  inspirations: [{type: 'autogenerated', dirName: 'inspirations'}],
  concepts: [{type: 'autogenerated', dirName: 'concepts'}],
  tutorials: [{type: 'autogenerated', dirName: 'tutorials'}]
};

module.exports = sidebars;

