import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  codeto: [{type: 'autogenerated', dirName: 'r2d2'}],
  andes: [{type: 'autogenerated', dirName: 'bb8'}],
  made: [{type: 'autogenerated', dirName: 'made'}],
};

module.exports = sidebars;

